- name: variables
  hosts: localhost
  vars:
    course: "Aws"
    Trainer: "Siva"
    Duration: "150hrs"
  tasks:
  - name: print override information
    vars:
      course: "DevOps"
    ansible.builtin.debug:
      msg: "Hii, we are learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
      
  - name: print information
    ansible.builtin.debug:
      msg: "Hii, we are learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}."