- name: variable from files
  hosts: localhost
  vars_file:
  - vars.yaml
  tasks:
    - name: print override information
      ansible.builtin.debug:
        msg: "Hii, we are learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}."