- name: variables from files
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hii, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."